# -*- coding: utf-8 -*-
"""4110E104 1004

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xJbRq6gLIWyN2Q4uxMezeoWYV16l4BDU
"""

x = input('Enter your name:')
print('Hello, ' + x)

a = eval(input("請輸入："))
a

b=a+9
b